### ISSUE TITLE
Full redesign/remake of the website

### ISSUE THREAD

**Issue by SkyzohKey** [Tox/tox.chat#158]
Hey guys.

I've started to work on a new design for the Tox website, even if people on IRC told me it wasn't needed, because I have the feeling we should have a «fancy» way to present our application to end users.

The way it currently is is not broken, but from a code and maintenance point it's a nightmare.

The goals of that rewrite are:
- To have a clean admin panel in which we could give clients maintainers a limited access so they could easily update their client-specific page ;
- To have an integrated blog engine that works well with the new design ;
- To provide a clean and simple documentation, linked to the c-toxcore repository for having it up-to-date ;
- To have a simple and intuitive website, that doesn't looks neerdish, making people more engaged and wanting to switch ; 
- To have a way for users to quickly report an issue via the website, without dealing with github, while a bot would post that issue on the appropriate repo.

This is a long project but it's worth it. I hope this will lead to better Tox adoption.

Here's a preview of the design, it's not finished and under thinking : https://app.evrybo.com/share/project/1955/12054/zdUvQqHbyoy1DtNlPKYW

Please send feedbacks, I hope this could help the most users to get secure while chatting.

Kiss 😂

**Comment by nurupo** [comment]
Sure, as long as:

  - The website is static, e.g. can be hosted on GitHub Pages
  - The static generator it uses can generate static websites as well as blogs
  - Whatever you use has good documentation and examples
  - Whatever you use has a reasonably sized community
  - It supports i18n
  - It has small installation footprint (including dependencies)
  - It's in Debian package repository
  - It uses a language that is commonly known / people who maintain the website know or could easily pick up (e.g. python is a pretty good choice)

it would be something I'd look into.

I'd advise keep using Jinja2 templates and Pelican -- the setup we have right now, as it already covers all of the points above, but instead improve it by doing the following:

  - Add i18n support (there is a plugin in Pelican for that) to everything (including blog mentioned next)
  - Add static blog, reusing the same design as for the website, so that it's seamless
    - Port all blog posts we currently have at blog.tox.chat over to the static blog
  - Add helpful Travis jobs
    - Check for 404 links
    - Check if images are web-optimized
    - Deploy a PR to GitHub Pages so that we could preview the change before merging it
  - Add doxygen doc generation for toxcore API, such that docs for all versions are kept, as well as for the latest version (e.g. tox.chat/docs/toxcore/0.1.4/ tox.chat/docs/toxcore/0.1.5/  tox.chat/docs/toxcore/latest/)
  - Change how website looks (I think it looks good as it is, but you might come up with something even better)

Oh, and don't forget to follow https://github.com/Tox/tox.chat#contribution-guidelines.

**Comment by nurupo** [comment]
I don't think down-voting SK is a good idea -- he is enthusiastic about contributing to the websitea and there are many things that could be improved with the website, so we just need to point him into the right direction instead of discouraging him with down-votes. I tried to do this in my last comment, pointing out, for example, that we want a static page website instead of dynamic CMS, that it should have a reasonably sized community, i.e. it shouldn't be written from scratch, there is a team of developers working on it and many users that use it in different setups and provide feedback to the developers on improving things, and so on.

**Comment by SkyzohKey** [comment]
The problem with static websites is that they are static lol. What I'd like to work on is a REAL website, fully featured to make our lives easier. I was thinking about Django, RoR or maybe Laravel for the back-end and pure HTML5 and CSS3, js would be used only to enhance the website visually, it should work without JS enabled.

What I was thinking is an admin panel tied to the website so we can update it in real time without having to make a PR or having to deal with Git 😉

**Comment by anoadragon453** [comment]
Also with mentioning that static pages work on darknet mirrors like ZeroNet while pages with server-side/PHP do not.

**Comment by SkyzohKey** [comment]
@anoadragon453 making the website available from zeronet is out of the scope of this issue. Also, it currently isn't available on it, so not really an issue.

**Comment by anoadragon453** [comment]
@SkyzohKey True, btw I have `qtox.bit` registered with namecoin currently if anyone wants to stick our site up on a few darknets.

**Comment by SkyzohKey** [comment]
Here's another link, allows me to better showcase the already done work on mockups : https://www.behance.net/gallery/52007569/Toxchat-redesign

**Comment by SkyzohKey** [comment]
This is no longer relevant. See https://github.com/Tox/tox.chat/issues/197. Closing.
