### ISSUE TITLE
Tor + Tox

### ISSUE THREAD

**Issue by MagnusChase464** [Tox/tox.chat#232]
I have an idea. What if one were able to combine TOR with Tox? It would enhance the anonymity of Tox users.

This idea of a TOR-based chat system has been around for ages, but so far, none of it has worked. Perhaps Tox could be the first.

**Comment by nurupo** [comment]
That's out of scope and unnecessary.

Out of scope: Tox doesn't aim to provide anonymity, the latency of using something like Tor would make real-time audio/video chats unusable.

Unnecessary: `torsocks` exists and many Tox clients allow users to set socks/http proxies to use, as such proxies are supported by libtoxcore. so you can already use Tox over Tor. (torsocks is probably better to use, because with proxies the DNS queries for bootstrap node hostnames are not proxied).
