### ISSUE TITLE
Images on the index page

### ISSUE THREAD

**Issue by Zer0-One** [Tox/tox.chat#68]
- [ ] The client images in the middle of the index page are too small
- [x] The mockup needs to be removed. I _never_ want to see the mockup used in place of a client screenshot again.

**Comment by nurupo** [comment]
- The little dots at the bottom of images are hard to notice and quite small to click at
  - Make the dots stand out a more. Perhaps move them under the image instead of them being on top the image?
  - Make it so the images change on their own instead of the user having to click on the small dots. [Here is a list of pure CSS3 (no JavaScript) image sliders from 2013, some of which also address the previous point](http://xdesigns.net/2013/08/css-slider/).
- Do images need to be that huge? [utox_mac.png](https://github.com/Tox/tox.chat/blob/master/src/img/client/utox_mac.png), for example, is 1,802px × 1,386px 212.71 KB image, and we have several such on the index page. Scaling down such images also results in blurriness, making the text from these images unreadable when presented on the index page. Similar is [utox_windows.png](https://raw.githubusercontent.com/Tox/tox.chat/master/src/img/client/utox_windows.png) and maybe some more.
- Some client images look like 4chan meme threads, which not everyone might get and, frankly, be turned off by them, thinking that it's an application for kid talk or for someone who gets all of this. Most of people's first introduction to Tox would be the index page of tox.chat, their first impression of Tox would be based on what they see on that page. Tox positions itself as a chat messenger for everyone, even your grandma, so the index page needs to provide the right first impression of this, so a causal conversation with the right balance of jokes (ones that don't require you to look up http://knowyourmeme.com/ every single word) and seriousness would be more suitable. We want people to see the index page and think something along the lines of "Wow, that's cool, I could use that instead of Skype/something." or "Let's try using this in our company!", not "Eh... what all these people with My Little Pony avatars are talking about? What's RMS? Who is Mr. Ayy Lmao and why is he so popular? Where is this Dankest place that this guy's grandma went to?".
- Client images are all over the place. Maybe there should be some specific requirement for them? At least for the index page. For example, toxic's image is a plain welcome image, it doesn't even show any contacts or a chat going on (well, okay, it tells that a group bot has come online, but having a screenshot of a conversation unfolding would be a lot more useful to users viewing the image). So a good requirement would be "a screenshot displaying a conversation unfolding, either in text, audio or video or any combination of there of". We might even go one step more, requiring all client screenshots to display exactly the same conversation with exactly the same people in contact list, standardizing the screenshots. This might be going a bit too far though, but it's a possibility.

**Comment by installgen2** [comment]
@nurupo

I will fix my little dots soon

I will make different image sizes and have media queries to select each one

see #9

**Comment by SkyzohKey** [comment]
I would suggest you to use this one since the code is nicely wrote: http://benschwarz.github.io/gallery-css/#item-2
