### ISSUE TITLE
Error when trying to install qTox on Debian

### ISSUE THREAD

**Issue by rugk** [Tox/tox.chat#93]
Brief description: Wrong entry in sources.list; could not find "debian/binary-amd64/Packages" in release file.

Operating System: Linux Mint Debian Edition 2.0
qTox version: /

Reproducible: Always

**Steps to reproduce:**
1. Follow the instructions at https://tox.chat/download.html#gnulinux for Debian/Ubuntu

**Observed Behavior:**
Literally:
> W: Fehlschlag beim Holen von https://pkg.tox.chat/debian/dists/nightly/InRelease  Erwarteter Eintrag »debian/binary-amd64/Packages« konnte in Release-Datei nicht gefunden werden (falscher Eintrag in sources.list oder missgebildete Datei).

(German version)

**Expected Behavior:**
Install qTox.

**Additional info:**
May be related to https://github.com/tux3/qTox/issues/2968

----
originally reported at https://github.com/tux3/qTox/issues/3030

**Comment by nurupo** [comment]
Waiting on the mentioned line from `/etc/apt/sources.list` file.

**Comment by rugk** [comment]
The `.list` file is 

    deb https://pkg.tox.chat/debian nightly debian

**Comment by nurupo** [comment]
That "debian" at the very end is what causing the issue. Instead of "debian" it should be either "jessie", "stretch", "sid", "vivid" or "wily", depending on which of those your deb-based distro is based.

Linux Mint website [says](https://www.linuxmint.com/download_all.php) that LInux Mint Debian 2 (Betsy) is based on Debian Jessie, so you should replace "debian" at the very end of that line with "jessie". After you do that, do `apt-get update` and try installing qtox again.

**Comment by nurupo** [comment]
Don't replace "debian" in "https://pkg.tox.chat/debian".

**Comment by rugk** [comment]
Now it works. So thanks for your help. I only have a run issue yet.

**Comment by rugk** [comment]
BTW just FYI the [package builds of qtox](https://github.com/tux3/qTox/issues/3063#issuecomment-202070265) are "broken".
So possibly you should add a warning to the installation instructions to make users aware that it won't work anyway. Just so they do not have to go all the way I did.
Currently I do not even know whether there are working builds at all.

**Comment by nurupo** [comment]
@tux3 ^

@rugk in what way are the packages broken? Unmet dependencies?  Are they broken for Debian/Ubuntu or just for Linux Mint Debian Edition 2? Because they were made for vanilla Debian/Ubuntu and we don't really know whether LMDE is compatible, besides that it's Debian-based so the packages might work.

**Comment by nurupo** [comment]
Oh, just noticed the link in your post.
