### ISSUE TITLE
qTox: "Best Tox client."

### ISSUE THREAD

**Issue by rugk** [Tox/tox.chat#94]
After [installing](https://github.com/tux3/qTox/issues/3030) I saw this funny description of `qTox` package:

![bestqtox](https://cloud.githubusercontent.com/assets/11966684/14065560/16bd77ea-f42f-11e5-999c-6f148f9c03bc.png)

Is not that discriminatory against the other clients?

**Comment by SkyzohKey** [comment]
That's a lie, Ricin is the best client :3

**Comment by ProMcTagonist** [comment]
I feel I can make a fairly substantiative argument defining best as the best for the majority of users according to the original goal of the project that qTox is in fact the best single Tox client, since it's got decent UX, works on Windows, and isn't hilariously broken visually.

I don't know who decided to play around with the package descriptions though. Should probably be changed to something actually informative.

**Comment by installgen2** [comment]
@ProMcTagonist regardless of it's status compared to other Tox clients I believe it should not have a name like this on a matter of principle.

**Comment by anoadragon453** [comment]
Yep, that's just egotistical. Were a community, not a competition.

**Comment by ProMcTagonist** [comment]
@installgen2 Yeah, not appropriate for the package description.

**Comment by nurupo** [comment]
tagging @tux3

(Might need to send him an email directly as I feel he just ignores all GitHub notifications because of qTox repo spam)

**Comment by tux3** [comment]
I appreciate the though, but I agree that a more neutral description would be nice!

**Comment by zetok** [comment]
>Is not that discriminatory against the other clients?

.

>@ProMcTagonist regardless of it's status compared to other Tox clients I believe it should not have a name like this on a matter of principle.

.

>Yep, that's just egotistical. Were a community, not a competition.

Yes, I too think that it should be changed to what was before, namely "The worst Tox client". /s

**Comment by alugarius** [comment]
qTox is not the best! No client is the best!
I prefer uTox because it has static binaries and is portable, qTox has more features (that I don't need).
Ricin just looks awesome and toxic is for users thay don't need this bloated gui stuff!

I need and support uTox, and other clients are also great! 
We have to stop fighting and work together, showing every client on the download (or repo explain) site.
uTox for "no Terminal  Users" 
qTox for "i want all this emoticons users"
Ricin for GTK Lovers. ... and so on! Making an download grid for binary downloads(ricin appimage, utox binary, AnTox apk ) and an how to add repo for qTox. That should do the stuff! As packet description I would call qTox "The big Qt tox client" and as uTox description "the portable lightweight tox client"
And ricin as "the GTK tox client"
Meep

**Comment by nurupo** [comment]
Should be fixed now, since qTox Linux packages were removed (see last blog posts if interested).
